services:
  web-server:
    env_file:
      - .env
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'